/**
 * CodeMie Analytics Aggregation System - Core Data Models
 *
 * Defines standardized data structures for aggregating analytics
 * from multiple AI coding agents (Gemini, Claude, Codex, CodeMie Native).
 */

// ============================================================================
// Core Entities
// ============================================================================

/**
 * Standardized session data across all agents
 */
export interface CodemieSession {
  // Identity
  sessionId: string;
  agent: 'gemini' | 'claude' | 'codex' | 'codemie-code' | 'deepagents';
  agentVersion: string;

  // Timing
  startTime: Date;
  endTime?: Date;
  durationMs?: number;

  // Context
  projectPath: string;
  projectHash?: string;
  gitBranch?: string;
  gitCommit?: string;

  // Configuration
  model: string;
  provider: string;
  profile?: string;

  // Aggregates
  userMessageCount: number;
  assistantMessageCount: number;
  toolCallCount: number;
  successfulToolCalls: number;
  failedToolCalls: number;
  fileModifications: number;

  // Tool usage breakdown (tool name -> count)
  toolUsage: Record<string, number>;

  // Tool status breakdown (tool name -> { success: number, failure: number })
  toolStatus: Record<string, { success: number; failure: number }>;

  // Model usage breakdown (model name -> message count)
  modelUsage: Record<string, number>;

  // Tokens (detailed breakdown)
  tokens: {
    // Input tokens
    input: number;              // Total input tokens
    output: number;             // Total output tokens

    // Cache tokens
    cacheRead: number;          // Cache hits (read from cache)
    cacheCreation: number;      // Cache writes (creating new cache entries)

    // Special token types
    reasoning?: number;         // Reasoning/thinking tokens (Claude)
    thoughts?: number;          // Thought tokens (Gemini)
    tool?: number;              // Tool-related tokens

    // Total
    total: number;              // Grand total of all tokens
  };

  // Status
  exitReason?: string;
  hadErrors: boolean;

  // File modification statistics
  fileStats?: {
    filesCreated: number;       // New files
    filesModified: number;      // Existing files changed
    filesDeleted: number;       // Files removed
    totalLinesAdded: number;    // Total lines generated by AI
    totalLinesRemoved: number;  // Total lines removed by AI
    totalLinesModified: number; // Total lines changed

    // Breakdown by language
    byLanguage: Record<string, {
      filesCreated: number;
      filesModified: number;
      linesAdded: number;
      linesRemoved: number;
    }>;

    // Breakdown by format category
    byFormat: Record<string, {
      filesCreated: number;
      filesModified: number;
      linesAdded: number;
      linesRemoved: number;
    }>;

    // Breakdown by tool
    byTool: Record<string, {
      count: number;
      linesAdded: number;
      linesRemoved: number;
    }>;
  };
}

/**
 * Standardized message data
 */
export interface CodemieMessage {
  // Identity
  messageId: string;
  sessionId: string;

  // Timing
  timestamp: Date;

  // Content
  role: 'user' | 'assistant';
  content: string;

  // Tokens (if available)
  tokens?: {
    input?: number;
    output?: number;
    cacheRead?: number;
    cacheCreation?: number;
    reasoning?: number;
    thoughts?: number;
    tool?: number;
    total?: number;
  };

  // Tools
  toolCalls?: CodemieToolCall[];

  // Model
  model?: string;
}

/**
 * Standardized tool call data
 */
export interface CodemieToolCall {
  // Identity
  toolCallId: string;
  messageId: string;
  sessionId: string;

  // Timing
  timestamp: Date;
  durationMs?: number;

  // Tool info
  toolName: string;
  toolArgs: Record<string, unknown>;

  // Result
  status: 'success' | 'failure' | 'aborted';
  result?: unknown;
  error?: string;

  // File modification flag
  modifiedFiles?: string[];
}

/**
 * File modification tracking
 */
export interface CodemieFileModification {
  // Identity
  sessionId: string;
  toolCallId: string;

  // Timing
  timestamp: Date;

  // File info
  filePath: string;
  operation: 'create' | 'update' | 'delete';

  // Metrics (enhanced tracking)
  linesAdded: number;        // Lines added by AI
  linesRemoved: number;      // Lines removed by AI
  linesModified?: number;    // Lines changed (for replace operations)
  sizeBytes?: number;        // Final file size

  // Operation details
  toolName: string;          // write_file, replace, smart_edit, etc.
  wasNewFile: boolean;       // true if file didn't exist before

  // Content metadata
  fileExtension: string;     // File extension (e.g., '.ts', '.md')
  language?: string;         // Programming language
  format?: string;           // File format category (code, docs, config, test, data)
}

// ============================================================================
// Query & Descriptor Types
// ============================================================================

/**
 * Options for querying sessions
 */
export interface SessionQueryOptions {
  projectPath?: string;
  dateFrom?: Date;
  dateTo?: Date;
  limit?: number;
  offset?: number;
}

/**
 * Session descriptor for lazy loading
 */
export interface SessionDescriptor {
  sessionId: string;
  agent: string;
  filePaths: string[]; // All files that contain this session's data
  metadata: Record<string, unknown>;
}

// ============================================================================
// Aggregation Options & Results
// ============================================================================

/**
 * Options for aggregating sessions
 */
export interface AggregationOptions extends SessionQueryOptions {
  agent?: string; // Filter by specific agent
  includeMessages?: boolean;
  includeToolCalls?: boolean;
  includeFileModifications?: boolean;
}

/**
 * Detailed session information
 */
export interface SessionDetails {
  session: CodemieSession;
  messages: CodemieMessage[];
  toolCalls: CodemieToolCall[];
  fileModifications: CodemieFileModification[];
}

/**
 * Analytics report structure
 */
export interface AnalyticsReport {
  summary: ReportSummary;
  sessions: CodemieSession[];
  breakdown: {
    byAgent: Record<string, AgentStats>;
    byModel: Record<string, ModelStats>;
    byProject: Record<string, ProjectStats>;
    byDay: Record<string, DayStats>;
  };
}

/**
 * Summary statistics
 */
export interface ReportSummary {
  totalSessions: number;
  totalMessages: number;
  totalTokens: number;
  totalToolCalls: number;
  totalFileModifications: number;
  averageSessionDuration: number;
  successRate: number;
}

/**
 * Agent-specific statistics
 */
export interface AgentStats {
  sessions: number;
  messages: number;
  tokens: number;
  toolCalls: number;
  fileModifications: number;
  averageDuration: number;
  successRate: number;
}

/**
 * Model-specific statistics
 */
export interface ModelStats {
  sessions: number;
  tokens: number;
  averageTokensPerSession: number;
}

/**
 * Project-specific statistics
 */
export interface ProjectStats {
  sessions: number;
  messages: number;
  fileModifications: number;
}

/**
 * Daily statistics
 */
export interface DayStats {
  date: string;
  sessions: number;
  messages: number;
  tokens: number;
}

// ============================================================================
// Report Options
// ============================================================================

/**
 * Options for generating reports
 */
export interface ReportOptions extends AggregationOptions {
  format?: 'json' | 'csv' | 'table';
  outputFile?: string;
}

// ============================================================================
// Export Formats
// ============================================================================

/**
 * JSON export format
 */
export interface JSONExport {
  version: '1.0.0';
  exportedAt: string;
  filters: AggregationOptions;
  sessions: CodemieSession[];
  messages?: CodemieMessage[];
  toolCalls?: CodemieToolCall[];
  fileModifications?: CodemieFileModification[];
}

/**
 * Remote analytics batch format
 */
export interface RemoteAnalyticsBatch {
  installationId: string;
  batchId: string;
  timestamp: string;
  sessions: CodemieSession[];
}
